version: '3.7'

services:
  triton-yolov8:
    restart: always
    image: "nvcr.io/nvidia/tritonserver:23.07-py3"
    container_name: triton-yolov8
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - ./models:/models
    command: sh -c "nvidia-smi && tritonserver --model-repository=/models"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
